import { db } from '@/lib/db';
import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const seedGames = [
      {
        title: "Doodle Jump",
        description: "Jump from platform to platform in this addictive vertical climber. Guide your doodler upward, avoid monsters, and collect power-ups!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/doodlejump/1/20200909162241/doodlejump-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/b6e80b1f95b641d2a50193f42a7d9af2/index.html",
        featured: true,
        tags: "arcade,jump,platformer,fun",
        plays: 12450,
        rating: 4.5,
      },
      {
        title: "Temple Run 2",
        description: "Run, slide, jump, and turn your way through dangerous temples and cliffs. How far can you go without falling?",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/templerun2/1/20220615101455/templerun2-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/1c5b6a4e4dd94a39864e1b286c5f07a6/index.html",
        featured: true,
        tags: "runner,endless,adventure,temple",
        plays: 28340,
        rating: 4.7,
      },
      {
        title: "Crossy Road",
        description: "Help your character cross busy roads, rivers, and train tracks in this charming endless hopper. Don't get squished!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/crossyroad/1/20210527131552/crossyroad-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/a34fbb1d62e34c9ba3419a3d7c2d5a90/index.html",
        featured: true,
        tags: "arcade,cross,road,fun,endless",
        plays: 19820,
        rating: 4.3,
      },
      {
        title: "Slither.io",
        description: "Grow your snake by consuming glowing orbs. Outmaneuver other players to become the longest snake in the arena!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/slitherio/1/20210616144341/slitherio-200x200-crop.jpg",
        gameUrl: "https://slither.io/",
        featured: true,
        tags: "snake,io,multiplayer,grow",
        plays: 45210,
        rating: 4.6,
      },
      {
        title: "Basketball Stars",
        description: "Compete in fast-paced 1v1 basketball matches. Dribble, shoot, and dunk your way to victory against players worldwide!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/basketballstars/1/20210503165323/basketballstars-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/8d2e4f3a1b5c4d6e7f8a9b0c1d2e3f4a/index.html",
        featured: false,
        tags: "sports,basketball,competition",
        plays: 8760,
        rating: 4.1,
      },
      {
        title: "Happy Wheels",
        description: "Race through obstacle courses with your favorite characters in this physics-based ragdoll game. Hilarious and challenging!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/happywheels/1/20210621110854/happywheels-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9/index.html",
        featured: false,
        tags: "physics,ragdoll,racing,funny",
        plays: 15670,
        rating: 4.4,
      },
      {
        title: "Tank Trouble",
        description: "Navigate maze-like arenas and blast your opponents with tank shells. Classic multiplayer tank combat at its finest!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/tanktrouble/1/20210517120025/tanktrouble-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0/index.html",
        featured: false,
        tags: "tank,battle,multiplayer,shooting",
        plays: 9430,
        rating: 4.0,
      },
      {
        title: "Stickman Hook",
        description: "Swing from point to point like a spider with a grapple hook. Time your swings perfectly to reach the finish line!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/stickmanhook/1/20210607135349/stickmanhook-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1/index.html",
        featured: false,
        tags: "stickman,swing,physics,fun",
        plays: 21300,
        rating: 4.5,
      },
      {
        title: "Drift Hunters",
        description: "Customize your car and drift on various tracks. Earn points for long, stylish drifts and build the ultimate drift machine!",
        category: "UNITY_WEBGL",
        thumbnailUrl: "https://images.crazygames.com/drifthunters/1/20220512094537/drifthunters-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2/index.html",
        featured: true,
        tags: "drift,cars,racing,3d",
        plays: 35670,
        rating: 4.8,
      },
      {
        title: "Madalin Stunt Cars 2",
        description: "Choose from supercars and perform insane stunts on massive ramps. Free roam in an open world multiplayer environment!",
        category: "UNITY_WEBGL",
        thumbnailUrl: "https://images.crazygames.com/madalinstuntcars2/1/20210604163826/madalinstuntcars2-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3/index.html",
        featured: true,
        tags: "cars,stunts,3d,multiplayer",
        plays: 41200,
        rating: 4.7,
      },
      {
        title: "Bullet Force",
        description: "Intense multiplayer FPS action with various weapons and maps. Create your own matches or jump into quick play!",
        category: "UNITY_WEBGL",
        thumbnailUrl: "https://images.crazygames.com/bulletforce/1/20220316144911/bulletforce-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4/index.html",
        featured: false,
        tags: "fps,shooting,multiplayer,action",
        plays: 27890,
        rating: 4.4,
      },
      {
        title: "Roblox",
        description: "Explore infinite worlds and build anything you can imagine. Play millions of games created by the community!",
        category: "UNITY_WEBGL",
        thumbnailUrl: "https://images.crazygames.com/roblox/1/20210524171450/roblox-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5/index.html",
        featured: false,
        tags: "sandbox,build,create,multiplayer",
        plays: 52340,
        rating: 4.6,
      },
      {
        title: "Super Smash Flash 2",
        description: "Fight with your favorite characters in this flash-style fighting game. Master combos and special moves to win!",
        category: "FLASH",
        thumbnailUrl: "https://images.crazygames.com/supersmashflash2/1/20210622154051/supersmashflash2-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6/index.html",
        featured: true,
        tags: "fighting,smash,characters,combo",
        plays: 18900,
        rating: 4.5,
      },
      {
        title: "Retro Bowl",
        description: "Manage your football team and lead them to victory! Call plays, manage roster, and become a gridiron legend.",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/retrobowl/1/20210823150605/retrobowl-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7/index.html",
        featured: false,
        tags: "football,sports,management,retro",
        plays: 24560,
        rating: 4.6,
      },
      {
        title: "Cookie Clicker",
        description: "Click the big cookie to earn cookies. Buy upgrades and buildings to automate your cookie production!",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/cookieclicker/1/20210602143738/cookieclicker-200x200-crop.jpg",
        gameUrl: "https://orteil.dashnet.org/cookieclicker/",
        featured: false,
        tags: "clicker,idle,cookies,incremental",
        plays: 38700,
        rating: 4.3,
      },
      {
        title: "Among Us Online",
        description: "Work together to complete tasks on a spaceship while impostors try to sabotage the mission. Can you spot the imposter?",
        category: "HTML5",
        thumbnailUrl: "https://images.crazygames.com/amongus/1/20211012125137/amongus-200x200-crop.jpg",
        gameUrl: "https://html5.gamedistribution.com/rvvASMiM/f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8/index.html",
        featured: true,
        tags: "social,deduction,multiplayer,space",
        plays: 56780,
        rating: 4.8,
      },
    ];

    // Clear existing games
    await db.game.deleteMany({});

    // Insert seed data
    for (const game of seedGames) {
      await db.game.create({ data: game });
    }

    return NextResponse.json({
      message: `Seeded ${seedGames.length} games successfully`,
      count: seedGames.length,
    });
  } catch (error) {
    console.error('Error seeding games:', error);
    return NextResponse.json({ error: 'Failed to seed games' }, { status: 500 });
  }
}
